### **Task 13 Submission**

**Question 1**
- Create a 6x6 NumPy array with random integers between 1 and 50.
- Display the array.

In [1]:
# 6 by 6 array array with random int between (1,50)

import numpy as np


array = np.random.randint(1,51, [6,6])
print("The 6 x 6 array:\n", array)

# Alternative using default range
rng = np.random.default_rng()
array_6 = rng.integers(1,51, size=(6,6))
print("The 6x6 using default range:\n", array_6)

The 6 x 6 array:
 [[32 18  8 17 28  1]
 [12  1 28 26  3 47]
 [20  1 13 11 48 13]
 [49 22 42 17 30 36]
 [36 47 15 11 20  3]
 [30  9 30 33 23  2]]
The 6x6 using default range:
 [[20  7 31 46  8 41]
 [39 38 39 10 48 34]
 [21 40 26  8 43 15]
 [14 21 41 36  9  9]
 [35  2 35 24 16 34]
 [49 10 22 37 47 43]]


**Question 2**

Extract the following from the array you created in 
- The first two rows.
- The last three columns. 
- All even numbers in the array.

In [14]:
# Extarcting the first two rows

arrays = np.array(array_6)
print("First two rows are:\n", arrays[0:2])

# Extracting the last three columns
arrays = np.array(array_6)
print("Last three columns are:\n", arrays[:, 3:])

# Extracting the even numbers from the array
arrays = np.array(array_6)
even_nums = arrays[arrays%2==0]
print("The even numbers are:\n", even_nums)

First two rows are:
 [[42 48 33 42 20  4]
 [ 6 30 16 40 44 21]]
Last three columns are:
 [[42 20  4]
 [40 44 21]
 [33 14  6]
 [11 44  7]
 [50 12 45]
 [12 13 20]]
The even numbers are:
 [42 48 42 20  4  6 30 16 40 44 36 14 14  6 42 24 32 44 12 50 12  6 12 20]


**Question 3**

Perform the following array transformations: 
- Reshape the array into a 3D (3, 2, 6) array. 
- Flatten the reshaped array back to 1D.

In [16]:
# Reshaping the array above into 3D
reshaped_3D = arrays.reshape(3, 2, 6)
print("Reshaped array (3by2by6):", reshaped_3D)

# Flattening the reshaped array to 1D

flattened = arrays.flatten()
print("Flatten array (1D):", flattened)


Reshaped array (3by2by6): [[[42 48 33 42 20  4]
  [ 6 30 16 40 44 21]]

 [[36  1 14 33 14  6]
  [42 24 32 11 44  7]]

 [[12 35 47 50 12 45]
  [ 7 45  6 12 13 20]]]
Flatten array (1D): [42 48 33 42 20  4  6 30 16 40 44 21 36  1 14 33 14  6 42 24 32 11 44  7
 12 35 47 50 12 45  7 45  6 12 13 20]


**Question 4**

- Generate a 4x4 identity matrix and 
- Replace the diagonal with numbers from 10 to 40, with a step of 10.

In [22]:
# Generate a 4x4 identity matrix
identity = np.eye(4)
print("Identity matrix:\n", identity)

diagonal_no = np.arange(10, 40, 10)
np.fill_diagonal(identity, diagonal_no)
print("The replaced numbers are:\n", diagonal_no)

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
The replaced numbers are:
 [10 20 30]


**Question 5**

Perform matrix multiplication between: 
- A 3x4 matrix of random integers (1-10) and A 4x3 matrix of random integers (1-10)


In [27]:
# Generate 3x4 random integers

matrix1 = np.random.randint(1,11, [3, 4])
matrix2 = np.random.randint(1,11, [4, 3])

# # Display the matrix
# matrix_1 = np.array([matrix1])
# matrix_2 = np.array([matrix2])

# Reshape matrix_2 to 3 rows 4 columns
reshape = matrix2.reshape(3,4)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Reshaped Matrix:\n", reshape)
print("Multiplication:", matrix1 * reshape)


Matrix 1:
 [[ 9  7  3  4]
 [ 2  9  2 10]
 [ 8  7  4  6]]
Matrix 2:
 [[ 6 10  3]
 [ 6  6  9]
 [ 6  5 10]
 [ 7  6  9]]
Reshaped Matrix:
 [[ 6 10  3  6]
 [ 6  9  6  5]
 [10  7  6  9]]
Multiplication: [[54 70  9 24]
 [12 81 12 50]
 [80 49 24 54]]


**Question 6**

Create a function that takes a 2D NumPy array as input and returns a new array where: 

- All even numbers are squared. 
- All odd numbers are replaced by -1.

In [ ]:
# Generate a function

def array_input():
    # Display output message
    print("---Operations on 2D NumPy---")

    # collect input
    arr_rows = np.array(int(input("Please enter the number of rows: ")))
    arr_cols = np.array(int(input("Please enter the number ofcolums: ")))

    # range the numbers and reshape the columns and rows
    array = np.arange(arr_rows*arr_cols).reshape(arr_rows, arr_cols)

    new_array = np.where(array % 2 == 0, array**2, -1)
    return new_array

print(array_input())

---Operations on 2D NumPy---
[[  0  -1   4  -1  16]
 [ -1  36  -1  64  -1]
 [100  -1 144  -1 196]
 [ -1 256  -1 324  -1]]
